services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - CLOUNDINARY_KEY=${CLOUNDINARY_KEY}
      - CLOUNDINARY_SECRET=${CLOUNDINARY_SECRET}
      - CLOUNDINARY_NAME=${CLOUNDINARY_NAME}
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sample_data.sql:/docker-entrypoint-initdb.d/sample_data.sql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
